# -*- coding: utf-8 -*-

do_tocmp_on_asserting = [
  ['attr', 0],
  ['replace', 0],
  ['upper', 0],
  ['lower', 0],
  ['escape', 0],
  ['e', 0],
  ['forceescape', 0],
  ['capitalize', 0],
  ['title', 0],
  ['default', 0],
  ['d', 0],
  ['join', 0],
  ['count', 0],
  ['dictsort', 0],
  ['sort', 0],
  ['length', 0],
  ['reverse', 0],
  ['center', 0],
  ['indent', 0],
  ['title', 0],
  ['capitalize', 0],
  ['first', 0],
  ['last', 0],
  ['random', 0],
  ['filesizeformat', 0],
  ['pprint', 0],
  ['truncate', 0],
  ['wordwrap', 0],
  ['wordcount', 0],
  ['int', 0],
  ['float', 0],
  ['string', 0],
  ['list', 0],
  ['urlize', 1],
  ['format', 0],
  ['trim', 0],
  ['striptags', 0],
  ['slice', 0],
  ['batch', 0],
  ['sum', 1],
  ['abs', 0],
  ['round', 0],
  ['groupby', 1],
  ['safe', 0],
  ['xmlattr', 1]
]

